#+TITLE: Pytest example: Assert that a certain exception is raised
#+DESCRIPTION: Pytest example: Assert that a certain exception is raised
#+TAGS: python, pytest, usage, unit-test
#+PROPERTY: header-args:sh :session *shell pytest-example-assert-that-a-certain-exception-is-raised sh* :results silent raw
#+PROPERTY: header-args:python :session *shell pytest-example-assert-that-a-certain-exception-is-raised python* :results silent raw
#+OPTIONS: ^:nil

** System environment

- Python 3.7.0

Python modules:

- pytest==3.6.0

** Assert that a certain exception is raised

#+BEGIN_SRC python :tangle src/test_assert_exception.py
import pytest


def f():
    raise SystemExit(1)


def test_mytest():
    with pytest.raises(SystemExit):
        f()
#+END_SRC

** Run the test

#+BEGIN_SRC sh
cd src
#+END_SRC

#+BEGIN_SRC sh
pytest
#+END_SRC

** References

1. https://docs.pytest.org/en/stable/getting-started.html#assert-that-a-certain-exception-is-raised
